# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9f7dcaad119420a7bbf4f16f2d21064b9b371e38051af7218b6ec6e74fd38c0ad23538f5c75fa0ddf91baa6337b16f9f04052940c60b2ff71a1e7b36f3caf95

test:
  secret_key_base: f2cf19d795888794451af53ec23595d78354aebdb384212db2739a5adfbd41e841dae407dba73ebda537832869b0eff9887330754b240721ef7fa5e8fd65c355

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
